package com.example.smartAttendence.domain;

import com.example.smartAttendence.entity.Room;
import com.example.smartAttendence.entity.Timetable;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.UUID;
import org.hibernate.annotations.UuidGenerator;
import org.locationtech.jts.geom.Polygon;

@Entity
@Table(name = "classroom_sessions")
public class ClassroomSession {

    @Id
    @GeneratedValue
    @UuidGenerator
    @Column(nullable = false)
    private UUID id;

    @ManyToOne(optional = false)
    @JoinColumn(name = "timetable_id", nullable = false)
    private Timetable timetable;

    @ManyToOne(optional = false)
    @JoinColumn(name = "room_id", nullable = false)
    private Room room;

    @ManyToOne(optional = false)
    @JoinColumn(name = "faculty_id", nullable = false)
    private User faculty;

    @Column(name = "auto_generated", nullable = false)
    private Boolean autoGenerated = false;

    @Column(name = "start_time", nullable = false)
    private Instant startTime;

    @Column(name = "end_time", nullable = false)
    private Instant endTime;

    @Column(name = "geofence_polygon", nullable = false, columnDefinition = "geometry(Polygon,4326)")
    private Polygon geofencePolygon;

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public Timetable getTimetable() {
        return timetable;
    }

    public void setTimetable(Timetable timetable) {
        this.timetable = timetable;
    }

    public Room getRoom() {
        return room;
    }

    public void setRoom(Room room) {
        this.room = room;
    }

    public User getFaculty() {
        return faculty;
    }

    public void setFaculty(User faculty) {
        this.faculty = faculty;
    }

    public Boolean getAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(Boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public Instant getStartTime() {
        return startTime;
    }

    public void setStartTime(Instant startTime) {
        this.startTime = startTime;
    }

    public Instant getEndTime() {
        return endTime;
    }

    public void setEndTime(Instant endTime) {
        this.endTime = endTime;
    }

    public Polygon getGeofencePolygon() {
        return geofencePolygon;
    }

    public void setGeofencePolygon(Polygon geofencePolygon) {
        this.geofencePolygon = geofencePolygon;
    }

    // AI and Autonomous Scheduling Support
    @Column(name = "timetable_id", insertable = false, updatable = false)
    private UUID timetableId;

    @Column(name = "subject")
    private String subject;

    @ManyToOne
    @JoinColumn(name = "section_id")
    private com.example.smartAttendence.entity.Section section;

    @Column(name = "is_exam_day", nullable = false)
    private Boolean isExamDay = false;

    @Column(name = "is_holiday", nullable = false)
    private Boolean isHoliday = false;

    @Column(name = "active", nullable = false)
    private Boolean active = true;

    // Getters for AI and scheduling
    public UUID getTimetableId() {
        return timetableId;
    }

    public String getSubject() {
        return subject;
    }

    public com.example.smartAttendence.entity.Section getSection() {
        return section;
    }

    public Boolean getIsExamDay() {
        return isExamDay;
    }

    public Boolean getIsHoliday() {
        return isHoliday;
    }

    public Boolean isActive() {
        return active;
    }

    // Setters for autonomous scheduler
    public void setTimetableId(UUID timetableId) {
        this.timetableId = timetableId;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public void setSection(com.example.smartAttendence.entity.Section section) {
        this.section = section;
    }

    public void setIsExamDay(Boolean isExamDay) {
        this.isExamDay = isExamDay;
    }

    public void setIsHoliday(Boolean isHoliday) {
        this.isHoliday = isHoliday;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }
}

