package com.example.smartAttendence.service.v1;

import com.example.smartAttendence.domain.ClassroomSession;
import com.example.smartAttendence.entity.Timetable;
import com.example.smartAttendence.repository.TimetableRepository;
import com.example.smartAttendence.repository.v1.ClassroomSessionV1Repository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.DayOfWeek;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.temporal.ChronoUnit;
import java.util.List;

@Service
@RequiredArgsConstructor
@Slf4j
public class SessionAutomationService {

    private final TimetableRepository timetableRepository;
    private final ClassroomSessionV1Repository classroomSessionRepository;

    /**
     * 🤖 AI ZERO-TOUCH SCHEDULER
     * Runs every minute to start sessions automatically based on the timetable.
     */
    @Scheduled(fixedRate = 60000)
    @Transactional
    public void runAutomationCycle() {
        log.debug("🤖 AI SCHEDULER: Starting automation cycle...");
        
        ZonedDateTime now = ZonedDateTime.now(ZoneId.of("Asia/Kolkata")); // Using IST as default
        DayOfWeek today = now.getDayOfWeek();
        LocalTime currentTime = now.toLocalTime().truncatedTo(ChronoUnit.MINUTES);

        // 1. AUTO-START SESSIONS
        autoStartSessions(today, currentTime);

        // 2. AUTO-END SESSIONS
        autoEndSessions(now.toInstant());
    }

    private void autoStartSessions(DayOfWeek day, LocalTime time) {
        // Find timetable entries starting in the current window (this minute)
        List<Timetable> startingSoon = timetableRepository.findByDayOfWeekAndStartTime(day, time);

        if (startingSoon.isEmpty()) return;

        log.info("🤖 AI SCHEDULER: Found {} slots starting at {} on {}", startingSoon.size(), time, day);

        for (Timetable slot : startingSoon) {
            try {
                // Check if session already exists for this slot today
                Instant startOfDay = LocalDate.now().atStartOfDay(ZoneId.of("Asia/Kolkata")).toInstant();
                Instant endOfDay = startOfDay.plus(1, ChronoUnit.DAYS);

                boolean exists = classroomSessionRepository.existsByTimetableIdAndDateRangeV1(
                        slot.getId(), startOfDay, endOfDay);

                if (!exists) {
                    startNewSession(slot);
                } else {
                    log.debug("Session already exists for timetable ID: {} today", slot.getId());
                }
            } catch (Exception e) {
                log.error("Failed to auto-start session for timetable {}: {}", slot.getId(), e.getMessage());
            }
        }
    }

    @Transactional
    protected void startNewSession(Timetable slot) {
        log.info("🚀 AI AUTOMATION: Auto-starting session for Subject: {} | Section: {}", slot.getSubject(), slot.getSection().getName());

        ClassroomSession session = new ClassroomSession();
        session.setTimetable(slot);
        session.setTimetableId(slot.getId());
        session.setSubject(slot.getSubject());
        session.setFaculty(slot.getFaculty());
        session.setRoom(slot.getRoom());
        session.setSection(slot.getSection());
        session.setIsExamDay(slot.getIsExamDay());
        session.setIsHoliday(slot.getIsHoliday());
        session.setActive(true);
        session.setAutoGenerated(true);

        // Copy Geofence from Room
        if (slot.getRoom() != null && slot.getRoom().getBoundaryPolygon() != null) {
            session.setGeofencePolygon(slot.getRoom().getBoundaryPolygon());
        }

        // Set Start and End Times
        LocalDate today = LocalDate.now();
        Instant startTime = slot.getStartTime().atDate(today).atZone(ZoneId.of("Asia/Kolkata")).toInstant();
        Instant endTime = slot.getEndTime().atDate(today).atZone(ZoneId.of("Asia/Kolkata")).toInstant();
        
        session.setStartTime(startTime);
        session.setEndTime(endTime);

        classroomSessionRepository.save(session);
        log.info("✅ AI AUTOMATION: Session created successfully [ID: {}]", session.getId());
    }

    private void autoEndSessions(Instant now) {
        List<ClassroomSession> expiredSessions = classroomSessionRepository.findByEndTimeBeforeAndActiveTrue(now);
        
        if (!expiredSessions.isEmpty()) {
            log.info("🧹 AI CLEANUP: Ending {} expired sessions automatically.", expiredSessions.size());
            for (ClassroomSession session : expiredSessions) {
                session.setActive(false);
                classroomSessionRepository.save(session);
                log.info("🏁 AI CLEANUP: Ended session for {}", session.getSubject());
            }
        }
    }
}
