package com.example.smartAttendence.repository.v1;

import com.example.smartAttendence.domain.ClassroomSession;
import com.example.smartAttendence.entity.Timetable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

@Repository
public interface ClassroomSessionV1Repository extends JpaRepository<ClassroomSession, UUID> {

    // ========== ORIGINAL METHODS FROM BASE REPOSITORY ==========
    
    List<ClassroomSession> findByFacultyId(UUID facultyId);
    List<ClassroomSession> findByRoomId(UUID roomId);
    long countByRoomId(UUID roomId);

    @Query("SELECT COUNT(cs) > 0 FROM ClassroomSession cs WHERE cs.timetable = :timetable AND cs.startTime BETWEEN :startTime AND :endTime")
    Boolean existsByTimetableAndStartTimeBetween(@Param("timetable") Timetable timetable, 
                                                 @Param("startTime") Instant startTime, 
                                                 @Param("endTime") Instant endTime);

    @Query("SELECT cs FROM ClassroomSession cs WHERE cs.autoGenerated = true AND cs.endTime > :now")
    List<ClassroomSession> findActiveAutoGeneratedSessions(@Param("now") Instant now);

    @Query("SELECT cs FROM ClassroomSession cs WHERE cs.timetable.faculty.id = :facultyId AND cs.startTime >= :startDate AND cs.startTime <= :endDate")
    List<ClassroomSession> findByFacultyAndDateRange(@Param("facultyId") UUID facultyId, 
                                                   @Param("startDate") Instant startDate, 
                                                   @Param("endDate") Instant endDate);

    @Query("SELECT cs FROM ClassroomSession cs WHERE cs.room.id = :roomId AND cs.startTime >= :startDate AND cs.startTime <= :endDate")
    List<ClassroomSession> findByRoomAndDateRange(@Param("roomId") UUID roomId, 
                                                  @Param("startDate") Instant startDate, 
                                                  @Param("endDate") Instant endDate);

    List<ClassroomSession> findByStartTimeBetween(Instant start, Instant end);
    
    @Query("SELECT cs FROM ClassroomSession cs WHERE cs.timetable.id = :timetableId AND cs.active = :active")
    Optional<ClassroomSession> findByTimetableIdAndActive(@Param("timetableId") UUID timetableId, 
                                                        @Param("active") Boolean active);
    
    @Query("SELECT cs FROM ClassroomSession cs WHERE cs.timetable.id = :timetableId AND cs.startTime >= :startOfDay AND cs.startTime < :endOfDay")
    Optional<ClassroomSession> findByTimetableIdAndDateRange(@Param("timetableId") UUID timetableId, 
                                                            @Param("startOfDay") Instant startOfDay,
                                                            @Param("endOfDay") Instant endOfDay);

    
    @Query("SELECT cs FROM ClassroomSession cs WHERE cs.timetable.section.id = :sectionId " +
           "AND cs.startTime <= :currentTime " +
           "AND cs.endTime >= :currentTime " +
           "AND cs.active = true")
    List<ClassroomSession> findActiveSessionsForSection(@Param("sectionId") UUID sectionId, 
                                                       @Param("currentTime") Instant currentTime);
    
    @Query("SELECT cs FROM ClassroomSession cs WHERE cs.room.id = :roomId " +
           "AND cs.startTime <= :currentTime " +
           "AND cs.endTime >= :currentTime " +
           "AND cs.active = true")
    List<ClassroomSession> findActiveSessionsInRoom(@Param("roomId") UUID roomId, 
                                                   @Param("currentTime") Instant currentTime);

    // ========== V1 METHODS ==========
    
    List<ClassroomSession> findByActiveTrue();

    @Query("SELECT cs FROM ClassroomSession cs WHERE cs.endTime < :cutoffTime AND cs.active = true")
    List<ClassroomSession> findByEndTimeBeforeAndActiveTrue(@Param("cutoffTime") Instant cutoffTime);

    @Query("SELECT COUNT(cs) > 0 FROM ClassroomSession cs WHERE cs.timetableId = :timetableId " +
           "AND cs.startTime >= :startOfDay AND cs.startTime < :endOfDay")
    Boolean existsByTimetableIdAndDateRangeV1(@Param("timetableId") UUID timetableId, 
                                             @Param("startOfDay") Instant startOfDay,
                                             @Param("endOfDay") Instant endOfDay);


    @Query("SELECT cs FROM ClassroomSession cs WHERE cs.faculty.id = :facultyId " +
           "AND DATE(cs.startTime) = DATE(:date) ORDER BY cs.startTime")
    List<ClassroomSession> findByFacultyIdAndDate(@Param("facultyId") UUID facultyId, @Param("date") Instant date);

    @Query("SELECT cs FROM ClassroomSession cs WHERE cs.room.id = :roomId " +
           "AND DATE(cs.startTime) = DATE(:date) ORDER BY cs.startTime")
    List<ClassroomSession> findByRoomIdAndDate(@Param("roomId") UUID roomId, @Param("date") Instant date);

    @Query("SELECT cs FROM ClassroomSession cs WHERE cs.section.id = :sectionId " +
           "AND DATE(cs.startTime) = DATE(:date) ORDER BY cs.startTime")
    List<ClassroomSession> findBySectionIdAndDate(@Param("sectionId") UUID sectionId, @Param("date") Instant date);

    List<ClassroomSession> findByIsExamDayTrue();

    @Query("SELECT cs FROM ClassroomSession cs WHERE cs.isExamDay = true " +
           "AND DATE(cs.startTime) = DATE(:date) ORDER BY cs.startTime")
    List<ClassroomSession> findExamSessionsByDate(@Param("date") Instant date);

    long countByActiveTrue();
    long countByIsExamDayTrue();
    long countByStartTimeAfter(Instant startTime);

    @Query("SELECT COUNT(cs) FROM ClassroomSession cs WHERE cs.active = true AND cs.section.department.id = :deptId")
    long countByActiveTrueAndDepartmentId(@Param("deptId") UUID deptId);

    @Query("SELECT COUNT(cs) FROM ClassroomSession cs WHERE cs.startTime > :startTime AND cs.section.department.id = :deptId")
    long countByStartTimeAfterAndDepartmentId(@Param("startTime") Instant startTime, @Param("deptId") UUID deptId);

    @org.springframework.data.jpa.repository.Modifying
    @org.springframework.transaction.annotation.Transactional
    @Query("DELETE FROM ClassroomSession cs WHERE cs.timetable.id = :timetableId")
    void deleteByTimetableId(@Param("timetableId") UUID timetableId);
    long countByTimetableId(UUID timetableId);

    @Query("SELECT COUNT(cs) FROM ClassroomSession cs WHERE cs.section.id = :sectionId AND cs.active = false")
    long countBySectionIdAndActiveFalse(@Param("sectionId") UUID sectionId);

    @Query("SELECT COUNT(cs) FROM ClassroomSession cs WHERE cs.section.id = :sectionId AND cs.active = false AND cs.startTime >= :since")
    long countBySectionIdAndActiveFalseAndStartTimeAfter(@Param("sectionId") UUID sectionId, @Param("since") Instant since);
}

