package com.example.smartAttendence.service.ai;

import com.example.smartAttendence.domain.AttendanceRecord;
import com.example.smartAttendence.domain.ClassroomSession;
import com.example.smartAttendence.domain.User;
import com.example.smartAttendence.entity.SecurityAlert;
import com.example.smartAttendence.entity.Timetable;
import com.example.smartAttendence.repository.v1.AcademicCalendarV1Repository;
import com.example.smartAttendence.repository.v1.AttendanceRecordV1Repository;
import com.example.smartAttendence.repository.v1.ClassroomSessionV1Repository;
import com.example.smartAttendence.repository.v1.SecurityAlertV1Repository;
import com.example.smartAttendence.repository.TimetableRepository;
import com.example.smartAttendence.repository.v1.UserV1Repository;
import com.example.smartAttendence.service.v1.NotificationService;
import com.google.cloud.firestore.Firestore;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.*;
import java.util.List;
import java.util.UUID;

@Service
@Slf4j
@RequiredArgsConstructor
public class AIAttendanceMonitorService {

    private final TimetableRepository timetableRepository;
    private final ClassroomSessionV1Repository sessionRepository;
    private final AttendanceRecordV1Repository attendanceRepository;
    private final UserV1Repository userRepository;
    private final SecurityAlertV1Repository alertRepository;
    private final NotificationService notificationService;
    private final AcademicCalendarV1Repository calendarRepository;
    private final AISpatialMonitoringEngine spatialEngine;
    private final AILearningOptimizer learningOptimizer;
    private final Firestore firestore;

    /**
     * 🤖 AI AUTONOMOUS MONITORING TASK
     * Runs every minute to sync timetable with live presence
     */
    @Scheduled(fixedRate = 60000)
    @Transactional
    public void monitorActiveSessions() {
        LocalDateTime now = LocalDateTime.now();
        LocalDate today = now.toLocalDate();
        DayOfWeek day = now.getDayOfWeek();
        LocalTime time = now.toLocalTime();

        if (calendarRepository.isHoliday(today)) {
            log.info("🤖 AI MONITOR [RESTING MODE]: Today is a holiday. Skipping autonomous scan.");
            return;
        }

        log.debug("🤖 AI MONITOR: Starting autonomous scan at {} {}", day, time);

        List<Timetable> activeSlots = timetableRepository.findByDayOfWeekAndStartTimeBeforeAndEndTimeAfter(day, time, time);

        for (Timetable slot : activeSlots) {
            if (Boolean.TRUE.equals(slot.getIsHoliday())) {
                if (slot.getHolidayDate() != null && !slot.getHolidayDate().equals(now.toLocalDate())) {
                    log.debug("🤖 AI MONITOR: Session '{}' - Holiday mismatch date. Proceeding.", slot.getSubject());
                } else {
                    log.info("🤖 AI MONITOR [RESTING MODE]: Session '{}' is holiday. Skipping.", slot.getSubject());
                    continue;
                }
            }
            processActiveSlot(slot, now);
        }
    }

    private void processActiveSlot(Timetable slot, LocalDateTime now) {
        Instant startOfDay = now.toLocalDate().atStartOfDay(ZoneId.systemDefault()).toInstant();
        Instant endOfDay = now.toLocalDate().plusDays(1).atStartOfDay(ZoneId.systemDefault()).toInstant();
        
        ClassroomSession session = sessionRepository.findByTimetableIdAndDateRange(slot.getId(), startOfDay, endOfDay)
                .orElse(null);

        if (session == null) {
            session = createAutomaticSession(slot, now);
        } else if (!session.isActive()) {
            session.setActive(true);
            session = sessionRepository.save(session);
        }

        if (timeIsAfterThreshold(slot.getStartTime(), now, 10)) {
            enforceAttendance(session, slot);
        }

        enforceWalkoutRules(session, slot);
        monitorStudentBehavior(session);
    }

    private ClassroomSession createAutomaticSession(Timetable slot, LocalDateTime now) {
        ClassroomSession session = new ClassroomSession();
        session.setTimetable(slot);
        session.setRoom(slot.getRoom());
        session.setFaculty(slot.getFaculty());
        session.setSection(slot.getSection());
        session.setSubject(slot.getSubject());
        session.setAutoGenerated(true);
        session.setActive(true);
        session.setIsExamDay(Boolean.TRUE.equals(slot.getIsExamDay()));
        session.setIsHoliday(Boolean.TRUE.equals(slot.getIsHoliday()));
        
        ZoneId zone = ZoneId.systemDefault();
        Instant start = now.toLocalDate().atTime(slot.getStartTime()).atZone(zone).toInstant();
        Instant end = now.toLocalDate().atTime(slot.getEndTime()).atZone(zone).toInstant();
        if (end.isBefore(start)) end = now.toLocalDate().plusDays(1).atTime(slot.getEndTime()).atZone(zone).toInstant();
        
        session.setStartTime(start);
        session.setEndTime(end);
        if (slot.getRoom() != null) session.setGeofencePolygon(slot.getRoom().getBoundaryPolygon());
        
        ClassroomSession savedSession = sessionRepository.save(session);
        notifySectionOnSessionStart(savedSession);
        return savedSession;
    }

    private void notifySectionOnSessionStart(ClassroomSession session) {
        List<User> students = userRepository.findBySectionId(session.getSection().getId());
        for (User student : students) {
            notificationService.sendSessionStartPrompt(student, session);
        }
    }

    private void monitorStudentBehavior(ClassroomSession session) {
        List<AttendanceRecord> presenceList = attendanceRepository.findBySessionIdOrderByRecordedAtDesc(session.getId());
        for (AttendanceRecord record : presenceList) {
            if ("PRESENT".equalsIgnoreCase(record.getStatus())) {
                boolean isSuspicious = spatialEngine.checkSuspiciousBehavior(record.getStudent().getId(), session.getId());
                if (isSuspicious) {
                    SecurityAlert alert = new SecurityAlert();
                    alert.setUser(record.getStudent());
                    alert.setAlertType("SUSPICIOUS_MOVEMENT");
                    alert.setAlertMessage("AI detected suspicious movement vector toward boundary.");
                    alert.setSeverity("MEDIUM");
                    alert.setConfidence(0.85);
                    alertRepository.save(alert);
                }
            }
        }
    }

    private boolean timeIsAfterThreshold(LocalTime startTime, LocalDateTime now, int minutes) {
        return now.toLocalTime().isAfter(startTime.plusMinutes(minutes));
    }

    private void enforceAttendance(ClassroomSession session, Timetable slot) {
        if (Boolean.TRUE.equals(session.getIsExamDay())) return;

        List<User> students = userRepository.findBySectionId(slot.getSection().getId());
        for (User student : students) {
            if (attendanceRepository.existsBySession_IdAndStudent_Id(session.getId(), student.getId())) continue;
            if (shouldBypassEnforcement(student, session)) continue;
            markAbsent(student, session, slot);
        }
    }

    private boolean shouldBypassEnforcement(User student, ClassroomSession session) {
        // A. Digital Hall Pass Bypass (Firestore Persistent)
        try {
            String docId = session.getId() + "_" + student.getId();
            if (firestore.collection("hall_passes").document(docId).get().get().exists()) return true;
        } catch (Exception e) { log.error("Hall pass check fail: {}", e.getMessage()); }

        // B. Transition Bypass
        if (spatialEngine.isRoomTransitionInProgress(session.getSection().getId())) return true;

        // C. Network Glitch Bypass
        return learningOptimizer.isGlobalNetworkGlitch(session.getSection().getId());
    }

    private void markAbsent(User student, ClassroomSession session, Timetable slot) {
        AttendanceRecord absentRecord = new AttendanceRecord();
        absentRecord.setStudent(student);
        absentRecord.setSession(session);
        absentRecord.setStatus("ABSENT");
        absentRecord.setRecordedAt(Instant.now());
        absentRecord.setNote("AI Automated Absence Marking");
        absentRecord.setAiDecision(true);
        absentRecord.setConfidence(1.0);
        attendanceRepository.save(absentRecord);

        notificationService.sendAttendanceAlert(student, slot, "AUTOMATED_ABSENCE");

        SecurityAlert alert = new SecurityAlert();
        alert.setUser(student);
        alert.setAlertType("AI_AUTO_ABSENT");
        alert.setAlertMessage("Student marked absent automatically (10m threshold)");
        alert.setSeverity("LOW");
        alert.setConfidence(0.98);
        alertRepository.save(alert);
    }

    private void enforceWalkoutRules(ClassroomSession session, Timetable slot) {
        List<AttendanceRecord> walkouts = attendanceRepository.findBySessionIdAndStatus(session.getId(), "WALK_OUT");

        for (AttendanceRecord record : walkouts) {
            User student = record.getStudent();
            String docId = session.getId() + "_" + student.getId();

            try {
                var timerDoc = firestore.collection("walkout_timers").document(docId).get().get();
                if (!timerDoc.exists()) continue;

                Instant walkoutStart = Instant.parse(timerDoc.getString("startTime"));
                if (Duration.between(walkoutStart, Instant.now()).toMinutes() >= 5) {
                    // Check Hall Pass
                    if (!firestore.collection("hall_passes").document(docId).get().get().exists()) {
                        log.warn("🤖 AI MONITOR [WALKOUT_EXPIRED]: Student {} - No return/pass. Revoking.", student.getName());
                        record.setStatus("ABSENT");
                        record.setAiDecision(true);
                        record.setNote("AI Automated Absence: Unauthorized Walkout > 5m");
                        attendanceRepository.save(record);

                        notificationService.sendAttendanceAlert(student, slot, "UNAUTHORIZED_WALKOUT");
                        
                        SecurityAlert alert = new SecurityAlert();
                        alert.setUser(student);
                        alert.setAlertType("WALKOUT_ABSENCE");
                        alert.setSeverity("HIGH");
                        alertRepository.save(alert);

                        firestore.collection("walkout_timers").document(docId).delete();
                    }
                }
            } catch (Exception e) { log.error("Walkout enforcement fail: {}", e.getMessage()); }
        }
    }
}
