name: Auto-Deploy to College Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Local Server
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Update Script
        shell: bash
        run: |
            chmod +x ./update-server.sh
            ./update-server.sh

